### ISSUE TITLE
handling of multi-echo MPRAGE

### ISSUE THREAD

**Issue by jcrdubois** [jmtyszka/bidskit#1]
it would be good to export the different echos -- in a manner similar to the one currently used for GE field maps

**Comment by jmtyszka** [comment]
Very doable - let me dig out a MEMPRAGE example and I'll implement this asap.

**Comment by jcrdubois** [comment]
I have coded something to handle MEMPRAGE:
-- discard series with separate echos
-- mark combined echo series as "acq-combME"

Also, for both T1w and T2w, I have added code to tag whether a series is bias-corrected or not, with "acq-NORM"

This currently results in a file name that may have 2 acq- fields, such as:
..._acq-combME_acq-NORM_T1w.nii

I'll upload my code in a bit -- just wanted to let you know so we don't do the work twice. I'll do it in a separate branch.

**Comment by jmtyszka** [comment]
Nice one and thank! One suggestion - leave the separate echo images intact, since they carry additional information and can be used to improve dural segmentation. Maybe add something to the acq- tag value to indicate echo number. Thanks also for adding the NORM suffix to the structurals - I was going to do that too, but you beat me too it :) Will very likely merge your features into the master branch.

**Comment by villalonreina** [comment]
Hi, currently what should be the correct way to modify the Protocol_Translator.json in order to handle multi-acquisitions? What should go in the "EXCLUDE_BIDS_Name" and "UNASSIGNED" fields?
