### ISSUE TITLE
events.tsv not properly created

### ISSUE THREAD

**Issue by Jihyuncindyhur** [jmtyszka/bidskit#49]
Hi, 

I have used dcm2bids.py to convert DICOM files from ABCD raw fMRI data into NIfTI files in BIDS format. Image(nii.gz) and JSON files were successfully created, but I have a problem with the 'events.tsv' file for each subject and run. It seems that running dcm2bids.py module has no problem of creating the event file, but it doesn't write any values after creating columns in the file (onset, duration, trial_type, and response_time). As I believe no issue has been reported on this matter, I was wondering if I was supposed to fill in those event time values manually. If not, could you advise me on how I can retrieve the needed information from DICOM event-related text files and fixing the corresponding events.tsv files? I am using ABCD raw task fMRI data and have already converted all into NIfTI files in BIDS, which passed the BIDS validator (meaning that the events.tsv files are present but just empty except the column names). Thank you!

**Comment by jmtyszka** [comment]
Hi Cindy,

dcm2bids is working as intended here. It's designed to convert DICOM series to BIDS only and create template task files for the user to complete (since the DICOM series won't contain any task timing information). We haven't yet developed support for integrating NDA-style task timing information (such as you'd find in the ABCD repository) into the conversion.
