### ISSUE TITLE
Subject/session names cannot contain "-" or "_"

### ISSUE THREAD

**Issue by villalonreina** [jmtyszka/bidskit#61]
I am trying the newest version of bidskit now. I have already used the older version. The first thing I noticed is that it does not accept subject names with "-" or "_". The previous version could handle it, nit this one. Nearly every dataset that I have worked on has subject IDs with wither "_" or "-". Changing this would require recoding the IDs across the whole dataset (cognitive data, etc), something that many collaborators would not agree with. Is there a way to change this? Thank you.  For now I'll use the older version.

**Comment by jmtyszka** [comment]
Thanks for raising this issue. I'll code up a work-around that allows '-' and '_' in the subject and session names. The original intention of excluding these characters was to avoid ambiguity when parsing subject and session IDs, since BIDS uses both characters as key-value separators. Since the keys are well defined, it shouldn't be a problem to parse the key-value pairs in a different way.

**Comment by jmtyszka** [comment]
This issue has been addressed in version 2018.8.16, which now allows '-' and '_' characters in any of the BIDS key values in the file name. These characters should be used with caution, and preferably avoided since they're prohibited by the BIDS specification in subject/session IDs and the resulting dataset won't validate if they're present.
