### ISSUE TITLE
--bind-fmaps not yet set up to work with --no-sessions

### ISSUE THREAD

**Issue by sarahoh** [jmtyszka/bidskit#98]
Calling bidskit with --bind-fmaps flag does not populate the IntendedFor field in the fmap/*epi.json files when used together with --no-sessions flag.

It seems that the `bind_fmaps` function in translate.py expects session directories even when --no-sessions is being used (see screenshot below).

![image (1)](https://user-images.githubusercontent.com/22419061/160733635-11ac1d4b-c6a8-4833-92f5-f23b697890d1.png)

**Comment by paola-g** [comment]
Hi, I encountered the same issue and came up with a (quite rudimental) solution here:
[https://github.com/paola-g/bidskit/blob/master/bidskit/fmaps.py](https://github.com/paola-g/bidskit/blob/master/bidskit/fmaps.py)

If you have any suggestions on how to make it more elegant/robust I could open a pull request.

**Comment by jmtyszka** [comment]
Hi @paola-g! Your solution looks eminently practical and if it works for most cases, all the better. The only thing I'd change is to pass the --no-sessions flag down to this function rather than check for zero length sessions arrays and maybe put the common code into a function. Go ahead and open a pull request and we can finish this up for @sarahoh

**Comment by jmtyszka** [comment]
I coded up a solution that uses the no-sessions flag and uses a more general approach to the subjects/sessions directories. Testing it now and will commit if it seems to work for a session-less structure.

**Comment by jmtyszka** [comment]
Just pushed a tested solution for the session-less fmap binding (v2022.5.18). Let me know if it does/doesn't work as intended (or IntendedFor :)) with your data @paola-g and @sarahoh.Thanks @paola-g for offering a fix! Ended up being a little more involved because the IntendedFor field needs to account for the lack of sessions.

**Comment by paola-g** [comment]
Thanks Mike, you were faster than me with the implementation! I will test on my data and report back.

**Comment by paola-g** [comment]
Just tested, seems to work fine!
